/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 duckerModel.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/duckerModel-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.57, 0.5, -0.24]} rotation={[-1.61, 0.19, -0.04]}>
        <group position={[0, 2.92, 173.29]} scale={[0.9, 1.02, 1.09]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.skin} position={[-13.47, 50.2, -16.57]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/duckerModel-transformed.glb')
